export const INSPECTOR_PORT = 'design-mode-inspector-rpc';
export const RPC_TIMEOUT = 15_000;
export const MAX_PAYLOAD = 12 * 1024 * 1024;
export const MESSAGE_TYPES = new Set(`SP_ACTIVATE SP_DEACTIVATE SP_CLEAR_ROUTE_CHANGES SP_CLEAR_SITE_CHANGES SP_OPEN_ROUTE SP_UPDATE_COMMENT DM_ANALYTICS_EVENT DM_ANALYTICS_STOP SP_TOGGLE_INSPECT SP_ADD_COMMENT SP_ADD_REGION_COMMENT SP_APPLY_PARENT_STYLE SP_APPLY_PRESET SP_APPLY_STYLE SP_APPLY_STYLES SP_APPLY_TOKEN SP_BATCH_APPLY_CHANGE SP_CANCEL_REGION_COMMENT SP_CLEAR_CHANGES SP_CONSOLIDATE_DETECTED SP_DELETE_PRESET SP_DESELECT SP_DOM_ACTION SP_EXPORT SP_FIND_MATCHING SP_FORCE_STATE SP_GET_CHANGES SP_GET_COMPUTED_CSS SP_GET_DESIGN_SYSTEM SP_GET_DESIGN_TOKENS SP_GET_DOM_TREE SP_GET_EFFECTIVE_BG SP_GET_FEEDBACK_SESSION SP_GET_MCP_STATUS SP_GET_MEDIA SP_GET_PAGE_FONTS SP_GET_PRESETS SP_GET_STATE SP_GET_TOKEN_USAGES SP_HOVER_ELEMENT SP_IMPORT_CHANGES SP_INSPECT_PAGE SP_MCP_REGISTER_TOKEN SP_MCP_REVOKE_TOKEN SP_OPEN_VSCODE SP_PANEL_CLOSING SP_PREVIEW_ANIMATION SP_PREVIEW_ORIGINAL SP_PREVIEW_TRANSITION_RULE SP_RECONFIGURE_TRANSPORT SP_REDO SP_REMOVE_CHANGE SP_REORDER_LAYER SP_REPLAY_APPEAR SP_RESET_ROOT_VAR SP_RESTORE_CHANGES SP_SAVE_PRESET SP_SCREENSHOT SP_SCROLL_TO_ELEMENT SP_SELECT_CHILD SP_SELECT_ELEMENT SP_SELECT_PARENT SP_SEND_TO_AGENT SP_SET_ATTRIBUTE SP_SET_COMMENT_RESOLVED SP_SET_COMMENT_PIN_OFFSET SP_SET_COMPUTED_LAYOUT_OVERLAY SP_SET_HTML SP_SET_INSPECT SP_SET_INSPECTOR_COLORS SP_SET_LAYOUT_GUIDES SP_SET_MULTI_SELECT_IDS SP_SET_ROOT_VAR SP_SET_TEXT SP_START_REGION_COMMENT SP_STOP_FEEDBACK_SESSION SP_TOGGLE_FREEZE SP_TOGGLE_VISIBILITY SP_TRIGGER_SHORTCUT SP_UNDO SP_UNHOVER_ELEMENT GET_LOCAL_MCP_TOKEN`.split(' '));
export const CONTENT_EVENTS = new Set(`AGENT_PRESENCE_UPDATE COMMENT_ERROR STYLE_OVERRIDE_ERROR CHANGES_UPDATE COMMENT_BUBBLE_CLICKED ELEMENT_DESELECTED ELEMENT_HOVERED_INFO ELEMENT_SELECTED FEEDBACK_SESSION_UPDATE HOVER_CAPABILITY_UPDATE LIVE_MOVE LIVE_RESIZE MULTI_SELECT_UPDATE OPEN_COMMENT_FOR_SELECTED REGION_CANCELLED REGION_DRAWN REQUEST_SCREENSHOT STATE_UPDATE SWITCH_TAB`.split(' '));
export const LOCAL_KEYS = new Set(`dm-analytics-consent-v1 dm-theme dm-color-format dm-capture-mode dm-mcp-port dm-mcp-auto-connect dm-mcp-mode dm-mcp-cloud-token dm-mcp-cloud-url dm-mcp-cloud-tenant dm-inspector-hover-color dm-inspector-select-color dm-overlay-margin-color dm-overlay-padding-color dm-input-unit dm-nudge-amount dm-custom-cursor dm-a11y-category dm-a11y-level dm-pip-size dm-pip-unsupported dm-launch-surface dm-shortcuts`.split(' '));
export const SYNC_KEYS = new Set(['dm_custom_presets']);
export const SESSION_KEYS = new Set(['dm-section-states', 'dm-tokens-tab']);
export function bounded(value: unknown): boolean {
  try { return JSON.stringify(value).length <= MAX_PAYLOAD; } catch { return false; }
}
export function eventChannel<T extends (...args: any[]) => any>() {
  const listeners = new Set<T>();
  return {
    addListener(fn: T) { listeners.add(fn); },
    removeListener(fn: T) { listeners.delete(fn); },
    hasListener(fn: T) { return listeners.has(fn); },
    emit(...args: Parameters<T>) { for (const fn of [...listeners]) fn(...args); },
    clear() { listeners.clear(); },
  };
}
