const fs = require('node:fs'), path = require('node:path'), assert = require('node:assert/strict');
const A = require('./panel-actions.cjs');
module.exports = async h => {
  const {panel, content, action, select, navigate, base, wait, out, version} = h;
  const rows = [], supplemental = [];
  const save = () => fs.writeFileSync(path.join(out, 'rows.json'), JSON.stringify({version, rows, supplemental}, null, 2));
  const snap = selector => panel(A.inspectSelector, selector);
  const click = async selector => { await panel(A.clickSelector, selector); await wait(400); };
  const input = async (selector, value) => { await panel(A.inputSelector, {selector, value}); await wait(500); };
  const edit = (prop, value) => input('input[data-dm-prop="' + prop + '"]', value);
  const style = (id, prop) => content(({id, prop}) => getComputedStyle(document.getElementById(id))[prop], {id, prop});
  const changes = () => h.send('SP_GET_CHANGES');
  const fresh = async (name, id) => {
    if ((await snap('[data-dm-action="close-tokens"]')).length) await action('close-tokens');
    await navigate(base + '/controls-' + name); await panel(A.showDesign); await wait(250);
    if (id) await select(id);
  };
  const advanced = async key => { if (!(await snap('[data-dm-advanced-body="' + key + '"]')).length) await click('[data-dm-advanced-toggle="' + key + '"]'); };
  const test = async (id, fn, remaining = '') => {
    const row = {id, status: 'running', remaining}; rows.push(row); save();
    try { row.observed = await fn(); row.status = remaining ? 'partial' : 'pass'; }
    catch (e) { row.status = 'fail'; row.error = String(e.stack); row.panel = await snap('body'); }
    save(); console.log(id, row.status, row.error || '');
  };
  await test('2.1', async () => { await fresh('leaf','copy'); const editor = await snap('[data-dm-richtext]'); assert.equal(editor.length,1); assert(editor[0].html.includes('Ordinary text')); const cmds = (await snap('[data-dm-richtext-cmd]')).map(e=>e.attributes['data-dm-richtext-cmd']); for(const c of ['bold','italic','underline','strikeThrough','insertUnorderedList','insertOrderedList','createLink']) assert(cmds.includes(c),c); return {editor,cmds}; });
  await test('2.2', async () => { await fresh('container','box'); assert.equal((await snap('[data-dm-richtext]')).length,0); assert(!(await h.panelText()).includes('Text Content')); return {editorCount:0}; });
  await test('2.9', async () => { await fresh('weight','copy'); const opts = await snap('[data-dm-prop="fontWeight"] option'); for(const [value,label] of [['100','Thin'],['300','Light'],['400','Regular'],['500','Medium'],['600','Semi Bold'],['700','Bold']]) assert(opts.some(o=>o.value===value && o.text.includes(label) && o.text.includes(value)),value); return opts; });
  await test('2.13', async () => { await fresh('toggles','copy'); const result=[]; for(const [toggle,prop,on,off] of [['bold','fontWeight','700','400'],['italic','fontStyle','italic','normal'],['underline','textDecorationLine','underline','none'],['strikethrough','textDecorationLine','line-through','none']]) { await click('[data-dm-text-toggle="'+toggle+'"]'); assert.equal(await style('copy',prop),on); await click('[data-dm-text-toggle="'+toggle+'"]'); assert.equal(await style('copy',prop),off); result.push({toggle,on,off}); } return result; });
  await test('2.22', async () => { await fresh('text-controls','copy'); const result=[]; for(const [prop,values] of [['textAlign',['left','center','right','justify']],['textTransform',['uppercase','lowercase','capitalize','none']]]) for(const value of values){await click('[data-dm-prop="'+prop+'"][data-dm-value="'+value+'"]');const actual=await style('copy',prop);assert.equal(actual,value);result.push({prop,value,actual});} for(const toggle of ['underline','strikethrough']) await click('[data-dm-text-toggle="'+toggle+'"]'); assert.match(await style('copy','textDecorationLine'),/underline/);assert.match(await style('copy','textDecorationLine'),/line-through/);return result; });
  await test('2.7', async () => { await fresh('rich-blur','copy'); await panel(A.editRichText,'Edited <b>bold text</b>'); await wait(600); assert.equal(await content(()=>{const clone=document.querySelector('#copy').cloneNode(true);for(const e of clone.querySelectorAll('[data-dm-id]'))e.removeAttribute('data-dm-id');return clone.innerHTML}),'Edited <b>bold text</b>'); const c=await changes(); assert.equal(c.textChanges.length,1);assert.equal(c.textChanges[0].isHtml,true);await panel(A.showChanges);await wait(450);assert((await snap('.dm-change-item')).some(r=>r.text.includes('bold text')));await navigate(base+'/controls-rich-blur');assert.equal(await content(()=>{const clone=document.querySelector('#copy').cloneNode(true);for(const e of clone.querySelectorAll('[data-dm-id]'))e.removeAttribute('data-dm-id');return clone.innerHTML}),'Edited <b>bold text</b>');return c; });
  await test('3.2a', async () => { await fresh('spacing','box'); const result=[];for(const prop of ['margin','padding']){await edit(prop,'20');assert.equal(await style('box',prop),'20px');await click('[data-dm-spacing-expand="'+prop+'"]');for(const [side,value] of [['Top','21'],['Right','22'],['Bottom','23'],['Left','24']]){await edit(prop+side,value);assert.equal(await style('box',prop+side),value+'px');} result.push({prop,value:await style('box',prop)});}const c=await changes();for(const prop of ['margin','padding'])for(const side of ['Top','Right','Bottom','Left'])assert(c.styleChanges.some(r=>r.property===prop+side || r.prop===prop+side),prop+side);return {result,changes:c}; });
  await test('3.2', async () => { await fresh('box-padding','box'); await advanced('layout'); await edit('paddingTop','24'); assert.equal(await style('box','paddingTop'),'24px');const c=await changes();assert(c.styleChanges.some(r=>JSON.stringify(r).includes('paddingTop')&&JSON.stringify(r).includes('24px')));return c; });
  await test('3.8', async () => { await fresh('flex','layout');await click('[data-dm-layout-mode="hstack"]');await advanced('layout');assert.equal(await style('layout','display'),'flex'); const controls=await snap('[data-dm-prop], [data-dm-gap-mode], [data-dm-children-align]');const html=controls.map(c=>c.html).join('');for(const term of ['flexWrap','data-dm-children-align','gap'])assert(html.includes(term),term);assert.equal(await style('layout','flexDirection'),'row');return controls; }, 'Horizontal-stack control replaces raw display/flex-direction select; wrap/justify/align/gap presence verified, vertical-direction control not yet asserted.');
  await test('3.9', async () => { await fresh('grid','layout');await click('[data-dm-layout-mode="grid"]');await advanced('layout');assert.equal(await style('layout','display'),'grid');const controls=await snap('[data-dm-prop]');for(const prop of ['gridTemplateColumns','gridTemplateRows','columnGap','rowGap'])assert(controls.some(c=>c.attributes['data-dm-prop']===prop),prop);return controls; });
  await test('3.12', async () => { await fresh('opacity-transform','box');await edit('__opacity_pct','50');await advanced('position');await edit('transform','rotate(3deg)');assert.equal(await style('box','opacity'),'0.5');const matrix=await style('box','transform');assert.match(matrix,/^matrix\(0\.99863/);return {opacity:await style('box','opacity'),matrix}; });
  await test('3.13', async () => { await fresh('shadow','box');await click('[data-dm-effects-menu]');await click('[data-dm-add-effect="drop-shadow"]'); const shadow=await style('box','boxShadow');assert.notEqual(shadow,'none');await click('[data-dm-effect-expand]');const controls=await snap('input[data-dm-prop^="__effd_"]');assert(controls.length>0);await input('input[data-dm-prop="'+controls.find(c=>c.attributes['data-dm-prop'].endsWith('_x')).attributes['data-dm-prop']+'"]','9');const after=await style('box','boxShadow');assert.notEqual(after,shadow);await panel(A.showChanges);await wait(450);assert((await snap('.dm-change-item')).some(r=>r.text.includes('boxShadow')));return {shadow,after,controls}; });
  await test('3.22', async () => { await fresh('motion-advanced','box');await advanced('motion');const controls=await snap('[data-dm-advanced-body="motion"]');assert(controls[0].text.includes('Transition'));return controls; },'Disclosure and existing Transition editor verified; conditional Animation/Transform/Motion-path/View-transition/Scroll-driven editors require a fixture authored with those effects.');
  await test('3.23', async () => { await fresh('appearance','box');const basic=await snap('[data-dm-section-body="dm-sec-appearance"]');assert.equal(basic.length,1);assert(!basic[0].text.includes('Opacity'));assert(!basic[0].text.includes('Corner radius'));assert.equal((await snap('[data-dm-prop="mixBlendMode"]')).length,0);assert.equal((await snap('[data-dm-prop="isolation"]')).length,0);await advanced('appearance');assert.equal((await snap('[data-dm-prop="mixBlendMode"]')).length,1);assert.equal((await snap('[data-dm-prop="isolation"]')).length,1);return {basic,advanced:await snap('[data-dm-advanced-body="appearance"]')}; },'Icon identity and hover tooltip rendering not asserted.');
  const tokens=async(name='tokens')=>{await fresh(name,'consumer');await action('open-tokens');await wait(700);await click('[data-tokens-tab="declared"]');};
  await test('8.1', async () => {await tokens('tabs');const tabs=await snap('[data-tokens-tab]');assert.deepEqual(tabs.map(t=>t.attributes['data-tokens-tab']),['declared','detected','defined']);await click('[data-tokens-tab="detected"]');assert.equal((await panel(A.readTokenTab))['dm-tokens-tab'],'detected');await action('close-tokens');await action('open-tokens');assert.equal((await snap('[data-tokens-tab="detected"]'))[0].attributes['data-active'],'true');return {tabs,stored:await panel(A.readTokenTab)};});
  await test('8.3', async () => {await tokens('token-edit');assert.equal(await style('consumer','padding'),'12px');await input('[data-dm-token-edit="--cert-space"]','24px');assert.equal(await style('consumer','padding'),'24px');const sheet=await content(()=>[...document.querySelector('#dm-token-overrides').sheet.cssRules].map(r=>r.cssText).join('\n'));assert(sheet?.includes('--cert-space'));return {sheet,padding:await style('consumer','padding')};});
  await test('8.4', async () => {await tokens('token-reset');await input('[data-dm-token-edit="--cert-space"]','24px');await input('[data-dm-token-edit="--cert-space"]','30px');assert.equal(await style('consumer','padding'),'30px');await click('[data-dm-token-reset="--cert-space"]');assert.equal(await style('consumer','padding'),'12px');return {restored:await style('consumer','padding')};});
  await test('8.9', async () => {await tokens('defined-empty');await click('[data-tokens-tab="defined"]');const text=await h.panelText();assert.match(text,/no.*preset|no.*defined|save.*preset/i);assert.equal((await snap('[data-dm-apply-preset]')).length,0);return text;});
  await test('8.24', async () => {await tokens('scoped');const before={inside:await style('scoped','color'),outside:await style('outside','color')};const scopes=await snap('[data-dm-token-scope-filter] option');const theme=scopes.find(o=>o.value==='.theme');if(theme)await input('[data-dm-token-scope-filter]','.theme');if(!(await snap('[data-dm-token-edit="--theme-primary"]')).length)await action('toggle-component-tokens');await input('[data-dm-token-edit="--theme-primary"]','#0000ff');assert.equal(await style('scoped','color'),'rgb(0, 0, 255)');assert.equal(await style('outside','color'),before.outside);await click('[data-dm-token-reset="--theme-primary"]');assert.equal(await style('scoped','color'),before.inside);return {before,scopes,reset:await style('scoped','color')};});
  await test('8.34', async () => {await tokens('token-undo');await input('[data-dm-token-edit="--cert-space"]','24px');await action('close-tokens');await action('undo');assert.equal(await style('consumer','padding'),'12px');assert.equal((await changes()).tokenChanges.length,0);await action('redo');assert.equal(await style('consumer','padding'),'24px');return await changes();},'Toolbar undo/redo exercised, not physical Ctrl/Cmd keyboard delivery.');
  await test('7.2', async () => {await fresh('mixed-filters','heading');await edit('fontSize','48');await edit('__opacity_pct','75');await select('copy');await panel(A.editRichText,'Edited <b>text</b>');await wait(500);await select('box');await action('duplicate');await select('heading');await action('comment');await input('[data-dm-comment-input]','Filter note');await action('submit-comment');await panel(A.showChanges);await wait(450);const filtered={};for(const [kind,count] of [['style',2],['text',1],['dom',1],['comment',1]]){await click('[data-dm-changes-filter="'+kind+'"]');filtered[kind]=await snap('.dm-change-item');assert.equal(filtered[kind].length,count);const chip=(await snap('[data-dm-changes-filter="'+kind+'"]'))[0];assert(chip.text.includes(String(count)));}await click('[data-dm-changes-filter="all"]');assert.equal((await snap('.dm-change-item')).length,5);return filtered;});
  await test('7.27',async()=>{const c=await changes();assert.equal(c.styleChanges.length,2);assert.equal(c.textChanges.length,1);assert.equal(c.domChanges.length,1);assert.equal(c.comments.length,1);const badge=await snap('[data-dm-tab="changes"]');assert.match(badge[0].text,/5/);return {c,badge};});
  await test('6.6',async()=>{await panel(A.showChanges);await wait(450);await click('[data-dm-changes-filter="comment"]');await click('[data-dm-toggle-resolved]');assert.equal((await changes()).comments[0].resolved,true);const controls=await snap('[data-dm-action],button');const resolved=controls.find(c=>c.text.trim().startsWith('Resolved')&&c.attributes['data-dm-comments-filter']);assert(resolved,'Resolved filter');await click('[data-dm-comments-filter="resolved"]');assert.equal((await snap('[data-dm-comment-item]')).length,1);return await changes();});
  await fresh('footer');const footer=await panel(A.inspectGeometry,'button');const cta=footer.find(b=>b.text.trim()==='Send to your AI agent');assert(cta,'Updated footer CTA');supplemental.push({name:'footer-cta-geometry',status:cta.rect.right<=cta.viewport.width && cta.scrollWidth<=cta.clientWidth?'pass':'fail',evidence:cta});save();await h.screenshot('footer-cta');
  if(rows.some(r=>r.status==='fail')||supplemental.some(r=>r.status==='fail'))throw Error('Current controls assertions failed');
};
