const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const A=require('./panel-actions.cjs');
module.exports=async h=>{
 const {panel,content,select,action,navigate,base,wait,out,version,screenshot}=h;
 const target=process.argv[2],results=[];
 const save=()=>fs.writeFileSync(path.join(out,'rows.json'),JSON.stringify({target,version,results},null,2));
 const snap=s=>panel(A.inspectSelector,s);
 const click=async s=>{await panel(A.clickSelector,s);await wait(450)};
 const input=async(s,value)=>{await panel(A.inputSelector,{selector:s,value});await wait(450)};
 const record=(ids,status,evidence,remaining='')=>{for(const id of ids)results.push({id,status,evidence,remaining});save()};
 const run=async(name,fn)=>{try{await fn()}catch(e){record([], 'partial',{});results.push({scenario:name,error:String(e),panel:await panel(A.panelText)});save();console.error(name,e)}};
 const fresh=async name=>{await navigate(base+'/'+name);await panel(A.showDesign);await wait(400)};
 const selectCard=async()=>{if(h.page)await h.page.locator('.card').first().click();else{await content(()=>true);await h.driver.findElement(require('selenium-webdriver').By.css('.card')).click()}await wait(400)};
 const changes=async()=>{await panel(A.showChanges);await wait(350)};
 const style=async(prop,value)=>{await panel(A.editProperty,{prop,value});await wait(500)};
 await run('comments',async()=>{
  await fresh('comments');await select('heading');await action('comment');await input('[data-dm-comment-input]','Certification comment');await action('submit-comment');await changes();
  const row=await snap('[data-dm-comment-item]');const pin=await content(()=>[...document.querySelectorAll('[id*="comment"],[class*="comment-pin"]')].map(e=>({html:e.outerHTML,rect:e.getBoundingClientRect().toJSON()})));
  assert(row.some(r=>r.text.includes('Certification comment')));assert(pin.length);record(['6.1','7.11'],'pass',{row,pin});
  await screenshot(target+'-comment');
  const pinPosition=await content(()=>{const e=document.querySelector('#heading').getBoundingClientRect(),p=document.querySelector('.dm-comment-pin').getBoundingClientRect();return {element:e.toJSON(),pin:p.toJSON()}});assert(Math.abs(pinPosition.element.right-(pinPosition.pin.left+pinPosition.pin.width/2))<1);assert(Math.abs(pinPosition.element.top-(pinPosition.pin.top+pinPosition.pin.height/2))<1);record(['6.3'],'pass',pinPosition);
  await panel(A.showDesign);await content(()=>{document.querySelector('.dm-comment-pin').click();return true});await wait(500);const pinView=await snap('[data-dm-edit-comment]');assert(pinView.length);record(['6.4'],'partial',{pinView,composer:await snap('[data-dm-comment-input]')},'Pin opens comment detail with an Edit button, not an immediate editing composer; UI contract drift.');
  await click('[data-dm-edit-comment]');await input('[data-dm-comment-input]','Edited certification comment');await action('submit-comment');await changes();assert((await panel(A.panelText)).includes('Edited certification comment'));
  await click('[data-dm-toggle-resolved]');await navigate(base+'/comments');await changes();const persisted=await snap('[data-dm-comment-item]');assert(persisted.some(r=>r.text.includes('Edited certification comment')&&r.html.includes('Reopen')));const persistedPins=await content(()=>[...document.querySelectorAll('[class*="comment-pin"]')].map(e=>e.outerHTML));assert.equal(persistedPins.length,1);assert(persistedPins[0].includes('✓ Edited certification comment'));assert(persistedPins[0].includes('opacity: 0.6'));record(['6.7'],'pass',{persisted,persistedPins});
  await click('[data-dm-delete-comment]');const confirm=await snap('[data-dm-action="confirm-delete-comment-confirm"]');if(confirm.length)await action('confirm-delete-comment-confirm');assert(!(await panel(A.panelText)).includes('Edited certification comment'));assert.equal(await content(()=>document.querySelectorAll('.dm-comment-pin').length),0);record(['6.5'],'pass',{edited:'Edited certification comment',deleted:true,pinsAfter:await content(()=>[...document.querySelectorAll('[class*="comment-pin"]')].map(e=>e.outerHTML))});
 });
 await run('changes',async()=>{
  await fresh('changes');await changes();const empty=await snap('body');assert(empty[0].text.includes('No changes yet'));const sparkles=await snap('svg[width="32"] path[d^="m12 3-1.9"]');assert.equal(sparkles.length,1);record(['7.1'],'pass',{empty:empty[0].text,sparkles});
  await panel(A.showDesign);await select('heading');await style('fontSize','48');await style('__opacity_pct','75');await style('borderRadius','10');await changes();
  const rows=await snap('.dm-change-item');assert.equal(rows.length,3);assert(rows.some(r=>r.text.includes('fontSize')&&r.text.includes('32px')&&r.text.includes('48px')));record(['7.7'],'pass',{rows,groups:await snap('[data-dm-change-group]')});
  const groupHeaders=await snap('[data-dm-change-group]');assert.equal(groupHeaders.length,1);assert(groupHeaders[0].html.includes('title="#heading"'));assert(groupHeaders[0].text.endsWith('3'));record(['7.12'],'pass',{rows:rows.length,groupHeaders});
  await input('[data-dm-changes-search]','fontSize');assert.equal((await snap('.dm-change-item')).length,1);await input('[data-dm-changes-search]','48px');assert.equal((await snap('.dm-change-item')).length,1);await action('clear-changes-search');record(['7.4'],'partial',{property:true,value:true},'Selector and comment text search not exercised.');
  await action('toggle-changes-sort');await click('[data-dm-changes-sort="newest"]');const newest=(await snap('.dm-change-item')).map(r=>r.text);await action('toggle-changes-sort');await click('[data-dm-changes-sort="oldest"]');const oldest=(await snap('.dm-change-item')).map(r=>r.text);assert.deepEqual(newest,[...oldest].reverse());await action('toggle-changes-sort');await click('[data-dm-changes-sort="element"]');record(['7.5'],'partial',{newest,oldest,byElement:await snap('.dm-change-item')},'By-element ordering across multiple elements not yet exercised.');
  const active=await snap('[data-dm-action="preview-original"]');await action('preview-original');const inactive=await snap('[data-dm-action="restore-changes"]');assert(inactive[0].html.includes('var(--dm-btn-bg)'));await action('restore-changes');record(['7.21'],'partial',{active,inactive},'UI contract drift: current UI is one Changes toggle, not two View Original/View Changes buttons.');
  const boxes=await snap('[data-dm-change-checkbox]');for(const b of boxes){const id=b.html.match(/data-dm-change-checkbox="([^"]+)"/)[1];await click('[data-dm-change-checkbox="'+id+'"]')};await action('revert-selected-changes');await wait(600);const after=await content(()=>{const s=getComputedStyle(document.querySelector('#heading'));return {font:s.fontSize,opacity:s.opacity,radius:s.borderRadius}});assert.deepEqual(after,{font:'32px',opacity:'1',radius:'0px'});assert((await panel(A.panelText)).includes('No changes yet'));record(['7.6'],'pass',{selected:boxes.length,after,empty:true});
 });
 await run('revert DOM',async()=>{
  await fresh('dom');await selectCard();await action('duplicate');await changes();const dup=await content(()=>[...document.querySelectorAll('.dm-clone')].map(e=>e.outerHTML));assert.equal(dup.length,1);await click('[data-dm-remove-change]');assert.equal(await content(()=>document.querySelectorAll('.dm-clone').length),0);record(['7.17'],'pass',{dup,after:0});
  await panel(A.showDesign);await select('delete');await action('delete');assert.equal(await content(()=>!!document.querySelector('#delete')),false);await changes();await click('[data-dm-remove-change]');const restored=await content(()=>document.querySelector('#delete')?.outerHTML);assert(restored?.includes('Delete me'));record(['7.18'],'pass',{restored});
 });
 await run('batch',async()=>{
  await fresh('batch');await select('heading');await style('borderRadius','15');await changes();const before=await snap('[data-dm-batch-apply]');assert(before[0].html.includes('background:none'));record(['7.24'],'pass',{before});await click('[data-dm-batch-apply]');const applied=await snap('[data-dm-batch-apply]');const radii=await content(()=>[...document.querySelectorAll('#heading,.card')].map(e=>getComputedStyle(e).borderRadius));if(radii.filter(x=>x==='15px').length!==1){record(['7.25','7.26'],'partial',{applied,radii,groups:await snap('[data-dm-change-group]'),body:await content(()=>getComputedStyle(document.body).borderRadius)},'Firefox native click selected body in this sequential scenario; unique-selector batch operation shown, requested-element fanout/unflag not certified. Selection discrepancy remains unclassified, not a confirmed product defect.');return}assert(applied[0].html.includes('background:var(--dm-accent-bg)'));record(['7.25'],'partial',{applied,radii},'Recorded selector is unique (UI says one matching element); multi-match fanout not established.');await click('[data-dm-batch-apply]');const unflag=await snap('[data-dm-batch-apply]');const after=await content(()=>[...document.querySelectorAll('#heading,.card')].map(e=>getComputedStyle(e).borderRadius));assert.deepEqual(after,radii);assert(unflag[0].html.includes('background:none'));record(['7.26'],'pass',{unflag,after});
 });
 await run('motion',async()=>{
  await fresh('motion');await select('heading');const before=await content(()=>document.getAnimations().map(a=>({id:a.effect.target.id,state:a.playState})));await action('toggle-freeze');const toggle=await snap('[data-dm-action="toggle-freeze"]');const paused=await content(()=>({animations:document.getAnimations().map(a=>({id:a.effect.target.id,state:a.playState})),video:document.querySelector('video').paused}));assert(toggle[0].html.includes('data-active="true"'));assert(paused.animations.every(a=>a.state==='paused'));await action('toggle-freeze');const resumed=await content(()=>document.getAnimations().map(a=>({id:a.effect.target.id,state:a.playState})));assert(resumed.some(a=>a.state==='running'));record(['9.9'],'partial',{before,toggle,paused,resumed},'CSS/WAAPI pause/resume verified. Fixture video has no media source; transition may complete before toggle. No claim of full video/transition coverage.');
 });
 await run('filters and counts',async()=>{
  await fresh('filters');await select('heading');await style('fontSize','48');await style('__opacity_pct','75');await style('borderRadius','10');await action('comment');await input('[data-dm-comment-input]','Searchable certification note');await action('submit-comment');await panel(A.showDesign);await select('copy');await action('duplicate');await changes();
  const all=await snap('[data-dm-changes-filter]'),badge=await snap('[data-dm-tab="changes"]');assert(badge[0].text.includes('5'));
  const filtered={};for(const [kind,count] of Object.entries({style:3,dom:1,comment:1,text:0,token:0})){await click('[data-dm-changes-filter="'+kind+'"]');filtered[kind]=await snap('.dm-change-item');assert.equal(filtered[kind].length,count)}await click('[data-dm-changes-filter="all"]');record(['7.2'],'partial',{all,filtered},'Positive Styles/DOM/Comments filters and empty Text/Tokens filters verified; positive Text/Tokens rows not exercised.');record(['7.27'],'partial',{badge},'Five-count badge verified for 3 style + 1 DOM + 1 comment; no text-change contribution exercised.');
  const search={};for(const query of ['#heading','fontSize','48px','Searchable certification note']){await input('[data-dm-changes-search]',query);search[query]=await snap('.dm-change-item');assert(search[query].length>0)}await action('clear-changes-search');record(['7.4'],'pass',{search});
 });
 await run('token files',async()=>{
  await fresh('tokenfiles');await action('open-tokens');await wait(700);
  let filename;
  if(h.panelPage){const downloaded=h.panelPage.waitForEvent('download');await action('tokens-export');const d=await downloaded;filename=path.join(out,d.suggestedFilename());await d.saveAs(filename)}else{const prior=new Set(fs.readdirSync(out));await action('tokens-export');for(let i=0;i<30;i++){const next=fs.readdirSync(out).find(f=>f.startsWith('design-system-')&&f.endsWith('.json')&&!prior.has(f));if(next){filename=path.join(out,next);break}await wait(200)}}
  assert(filename,'Download must exist');const text=fs.readFileSync(filename,'utf8'),payload=JSON.parse(text);assert.equal(payload.kind,'design-mode-design-system');assert(payload.tokens.some(t=>JSON.stringify(t).includes('--cert-space')));
  await panel(A.importFile,{selector:'[data-dm-tokens-import]',name:'roundtrip.json',text});await wait(800);const imported=await panel(A.panelText);assert(imported.includes('--cert-space'));
  await panel(A.importFile,{selector:'[data-dm-tokens-import]',name:'foreign.json',text:'{"unrelated":true}'});await wait(100);const rejected=await panel(A.panelText);assert(/not a Design Mode|invalid|not.*valid|missing/i.test(rejected));
  record(['8.15'],'pass',{filename:path.basename(filename),payload,imported,rejected});
 });
 save();console.log(JSON.stringify({target,results},null,2));assert.equal(results.filter(r=>r.error).length,0,'Every executed scenario must finish');
};
