const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
module.exports = async h => {
  await require('./review.cjs')(h);
  const panel = h.panelPage;
  const radius = panel.locator('input[data-dm-prop^="__effd_lblur_"]');
  assert(await radius.isDisabled());
  await radius.evaluate(el => {
    el.value = '8';
    el.dispatchEvent(new Event('input', {bubbles:true}));
    el.dispatchEvent(new Event('change', {bubbles:true}));
    el.dispatchEvent(new KeyboardEvent('keydown', {key:'Enter', bubbles:true}));
  });
  await h.wait(400);
  const hidden = await h.content(() => getComputedStyle(document.querySelector('#effect')).filter);
  assert.equal(hidden, 'contrast(2)');
  await panel.locator('[data-dm-effect-toggle]').click(); await h.wait(400);
  const restored = await h.content(() => getComputedStyle(document.querySelector('#effect')).filter);
  assert.equal(restored, 'blur(4px) contrast(2)');
  assert.equal(await radius.inputValue(), '4');
  assert(!(await radius.isDisabled()));
  await panel.locator('[data-dm-effects-menu]').click();
  await panel.locator('[data-dm-add-effect="inner-shadow"]').click(); await h.wait(400);
  const row = panel.locator('[data-dm-effect-row]').filter({has: panel.locator('[data-dm-effect-expand]')});
  await row.locator('[data-dm-effect-expand]').click();
  await row.locator('[data-dm-effect-toggle]').click(); await h.wait(400);
  const editor = row.locator('fieldset[data-dm-effect-editor]');
  assert.equal(await editor.getAttribute('disabled'), '');
  const inputs = editor.locator('input, select, button');
  assert(await inputs.count() > 0);
  for (let i=0;i<await inputs.count();i++) assert(await inputs.nth(i).isDisabled());
  const before = await h.content(() => getComputedStyle(document.querySelector('#effect')).boxShadow);
  await editor.locator('input[data-dm-prop]').first().evaluate(el => {el.value='99';el.dispatchEvent(new Event('change',{bubbles:true}));});
  await h.wait(400);
  assert.equal(await h.content(() => getComputedStyle(document.querySelector('#effect')).boxShadow), before);
  assert(!(await row.locator('[data-dm-effect-toggle]').isDisabled()));
  assert(!(await row.locator('[data-dm-effect-remove]').isDisabled()));
  await row.locator('[data-dm-effect-toggle]').click(); await h.wait(400);
  const shadow = await h.content(() => getComputedStyle(document.querySelector('#effect')).boxShadow);
  assert.match(shadow, /inset/);
  assert.equal(await editor.getAttribute('disabled'), null);
  await row.locator('[data-dm-effect-remove]').click(); await h.wait(400);
  assert.equal(await h.content(() => getComputedStyle(document.querySelector('#effect')).boxShadow), 'none');
  const observed={hidden,restored,expandedEditorDisabled:true,syntheticEditsBlocked:true,toggleRemoveUsable:true,shadow};
  fs.writeFileSync(path.join(h.out,'restore.json'),JSON.stringify(observed,null,2));
  console.log(JSON.stringify(observed));
};
